# Generated by Django 4.1 on 2023-06-04 11:43



from django.db import migrations
import pandas as pd


def insert_data(apps,schema_editor):

    Bands = apps.get_model("bands_ratings", "Bands")
    excel_data = pd.read_excel('/Users/samuelbridge/Documents/Download_fest_bands.xlsx')

    data = excel_data.values

    for band, stage, days in data:
        Bands.objects.create(band_name=band, stage_name=stage, day=days)


class Migration(migrations.Migration):

    dependencies = [
        ('bands_ratings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_data),

    ]
