# Generated by Django 4.1 on 2023-06-04 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands_ratings', '0002_auto_20230604_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='bands',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='bands_ratings.bands'),
        ),
    ]
